apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-example
  namespace: elastic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
